"""Plural environments, evaluation, routing, and tracing."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from plural.agents import Agent
from plural.catalog import ModelCatalog, ModelSpec, estimate_cost
from plural.client import Client, Plural
from plural.common import (
    ErrorCode,
    ExecutionTarget,
    HarnessCapability,
    content_hash,
    stable_id,
)
from plural.environments import (
    Action,
    Environment,
    ExecutionLimits,
    HarnessPolicy,
    Observation,
    Resource,
    Runtime,
    Secret,
    State,
    TraceDataset,
    TraceFilter,
    action,
    rewarder,
)
from plural.errors import (
    AuthenticationError,
    BudgetExceededError,
    ConfigurationError,
    ConflictError,
    ContentFilterError,
    ContextLengthError,
    InvalidRequestError,
    NotFoundError,
    PluralError,
    ProviderUnavailable,
    RateLimitError,
    TimeoutError,
    is_retryable,
)
from plural.execution import JobStore, Trial
from plural.harness import Harness, HarnessOutput
from plural.jobs import (
    AgentAggregate,
    ArtifactManifest,
    ArtifactManifestEntry,
    ArtifactReference,
    ExecutionStatus,
    Job,
    JobMode,
    JobPlan,
    JobResult,
    ProgressEvent,
    RetryPolicy,
    TITORecord,
    TrialExecution,
    TrialReceipt,
    TrialResult,
    TrialSpec,
    TrialStatus,
    VerifierResult,
)
from plural.project import (
    CatalogContext,
    Resolver,
)
from plural.project import (
    dump as dump_project,
)
from plural.project import (
    dumps as dumps_project,
)
from plural.project import (
    load as load_project,
)
from plural.sandbox import (
    Capability,
    DaytonaProvider,
    DeclarativeImage,
    DockerProvider,
    LocalProvider,
    NetworkMode,
    ProviderRegistry,
    SandboxProvider,
    SandboxRequirements,
)
from plural.studio import Studio
from plural.tasks import (
    Benchmark,
    BenchmarkDiff,
    Task,
    TaskPin,
)
from plural.tracing import (
    JSONLSink,
    Outcome,
    Redactor,
    Sampler,
    SQLiteSink,
    Trace,
    TraceContext,
    TraceKind,
    TraceWriter,
)
from plural.trajectory import Trajectory, TrajectoryEvent, normalize_trajectory
from plural.types import ChatRequest, ChatResponse, Message, Tool, Usage
from plural.verifiers import (
    AgentVerifier,
    DeterministicVerifier,
    Episode,
    EpisodeUsage,
    HumanVerifier,
    RubricCriterion,
    Verifier,
    VerifierOutput,
    VerifierRuntime,
)

try:
    __version__ = version("plural")
except PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = [
    "Action",
    "Agent",
    "AgentAggregate",
    "AgentVerifier",
    "ArtifactManifest",
    "ArtifactManifestEntry",
    "ArtifactReference",
    "AuthenticationError",
    "Benchmark",
    "BenchmarkDiff",
    "BudgetExceededError",
    "Capability",
    "CatalogContext",
    "ChatRequest",
    "ChatResponse",
    "Client",
    "ConfigurationError",
    "ConflictError",
    "ContentFilterError",
    "ContextLengthError",
    "DaytonaProvider",
    "DeclarativeImage",
    "DeterministicVerifier",
    "DockerProvider",
    "Episode",
    "EpisodeUsage",
    "Environment",
    "ErrorCode",
    "ExecutionLimits",
    "ExecutionStatus",
    "ExecutionTarget",
    "Harness",
    "HarnessCapability",
    "HarnessOutput",
    "HarnessPolicy",
    "HumanVerifier",
    "InvalidRequestError",
    "JSONLSink",
    "Job",
    "JobMode",
    "JobPlan",
    "JobResult",
    "JobStore",
    "LocalProvider",
    "Message",
    "ModelCatalog",
    "ModelSpec",
    "NetworkMode",
    "NotFoundError",
    "Observation",
    "Outcome",
    "Plural",
    "PluralError",
    "ProgressEvent",
    "ProviderRegistry",
    "ProviderUnavailable",
    "RateLimitError",
    "Redactor",
    "Resource",
    "Resolver",
    "RetryPolicy",
    "Runtime",
    "RubricCriterion",
    "SQLiteSink",
    "Sampler",
    "SandboxProvider",
    "SandboxRequirements",
    "Secret",
    "State",
    "Studio",
    "TITORecord",
    "Task",
    "TaskPin",
    "TimeoutError",
    "Tool",
    "Trace",
    "TraceContext",
    "TraceDataset",
    "TraceFilter",
    "TraceKind",
    "TraceWriter",
    "Trajectory",
    "TrajectoryEvent",
    "Trial",
    "TrialExecution",
    "TrialReceipt",
    "TrialResult",
    "TrialSpec",
    "TrialStatus",
    "Usage",
    "Verifier",
    "VerifierOutput",
    "VerifierResult",
    "VerifierRuntime",
    "__version__",
    "action",
    "content_hash",
    "dump_project",
    "dumps_project",
    "estimate_cost",
    "is_retryable",
    "load_project",
    "normalize_trajectory",
    "rewarder",
    "stable_id",
]
