"""Plural: unified LLM routing with first-class traces, environments, and benchmarks.

Examples:
    >>> from plural import __version__
    >>> isinstance(__version__, str)
    True
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from plural.agents import (
    AgentArtifact,
    AgentExperience,
    AgentInstance,
    AgentMemory,
    AgentSkill,
)
from plural.benchmarks import (
    Benchmark,
    CaseKey,
    CaseResult,
    ModelStats,
    Report,
    RunManifest,
    TaskDatasetMetadata,
    TaskSetMetadata,
    WinRatePair,
)
from plural.catalog import ModelCatalog, ModelSpec, estimate_cost
from plural.client import Client, Plural
from plural.domain import (
    AgentBinding,
    AgentInstanceRef,
    AgentTemplate,
    BenchmarkDefinition,
    BenchmarkSpec,
    EnvironmentIdentity,
    EnvironmentManifest,
    EnvironmentResource,
    EnvironmentRuntime,
    ErrorCode,
    ExecutionLimits,
    ExecutionTarget,
    FileDeclaration,
    Guardrail,
    HarnessBinding,
    HarnessCapability,
    HarnessManifest,
    HarnessPackage,
    HarnessPolicy,
    HarnessStamp,
    JobLock,
    JobPlan,
    JobResult,
    JobSpec,
    NativeAction,
    PackageSource,
    RetryPolicy,
    RoutingSpec,
    RuntimeSpec,
    TaskDefinition,
    TrialReceipt,
    TrialResult,
    TrialSpec,
    VerifierManifest,
    content_hash,
    resolve_harness_stamp,
    stable_id,
)
from plural.environments import (
    ActionResult,
    Dataset,
    Environment,
    PluralPolicy,
    Policy,
    ScriptedPolicy,
    StopReason,
    TaskData,
    TaskDataset,
    TraceDataset,
    TraceFilter,
)
from plural.errors import (
    AuthenticationError,
    BudgetExceededError,
    ConfigurationError,
    ConflictError,
    ContentFilterError,
    ContextLengthError,
    InvalidRequestError,
    NotFoundError,
    PluralError,
    ProviderUnavailable,
    RateLimitError,
    TimeoutError,
    is_retryable,
)
from plural.execution import Job, JobStore, Trial
from plural.harness import native_actions_v1, native_chat_v1
from plural.sandbox import (
    Capability,
    DaytonaProvider,
    DeclarativeImage,
    DockerProvider,
    LocalProvider,
    NetworkMode,
    ProviderRegistry,
    SandboxProvider,
    SandboxRequirements,
)
from plural.studio import RemoteAgent as Agent
from plural.studio import Studio
from plural.tracing import (
    JSONLSink,
    Outcome,
    Redactor,
    Sampler,
    SQLiteSink,
    Trace,
    TraceContext,
    TraceKind,
    TraceWriter,
)
from plural.types import ChatRequest, ChatResponse, Message, Tool, Usage

try:
    __version__ = version("plural")
except PackageNotFoundError:  # pragma: no cover
    __version__ = "0.0.0"

__all__ = [
    "ActionResult",
    "Agent",
    "AgentArtifact",
    "AgentBinding",
    "AgentExperience",
    "AgentInstance",
    "AgentMemory",
    "AgentSkill",
    "AgentInstanceRef",
    "AgentTemplate",
    "AuthenticationError",
    "Benchmark",
    "BenchmarkDefinition",
    "BenchmarkSpec",
    "BudgetExceededError",
    "CaseKey",
    "CaseResult",
    "ChatRequest",
    "ChatResponse",
    "Client",
    "ConfigurationError",
    "ConflictError",
    "ContentFilterError",
    "ContextLengthError",
    "Dataset",
    "Environment",
    "EnvironmentIdentity",
    "EnvironmentManifest",
    "EnvironmentResource",
    "EnvironmentRuntime",
    "ErrorCode",
    "ExecutionLimits",
    "ExecutionTarget",
    "FileDeclaration",
    "Guardrail",
    "HarnessBinding",
    "HarnessCapability",
    "HarnessManifest",
    "HarnessPackage",
    "HarnessPolicy",
    "HarnessStamp",
    "InvalidRequestError",
    "JSONLSink",
    "Job",
    "JobLock",
    "JobPlan",
    "JobResult",
    "JobSpec",
    "JobStore",
    "Message",
    "ModelCatalog",
    "ModelSpec",
    "ModelStats",
    "NativeAction",
    "NotFoundError",
    "Outcome",
    "PackageSource",
    "Plural",
    "PluralError",
    "PluralPolicy",
    "Policy",
    "ProviderUnavailable",
    "RateLimitError",
    "Redactor",
    "Report",
    "RetryPolicy",
    "RoutingSpec",
    "RuntimeSpec",
    "RunManifest",
    "SQLiteSink",
    "Sampler",
    "Studio",
    "ScriptedPolicy",
    "StopReason",
    "TaskData",
    "TaskDefinition",
    "TaskDataset",
    "TaskDatasetMetadata",
    "TaskSetMetadata",
    "TimeoutError",
    "Tool",
    "Trace",
    "TraceContext",
    "TraceDataset",
    "TraceFilter",
    "TraceKind",
    "TraceWriter",
    "TrialReceipt",
    "TrialResult",
    "TrialSpec",
    "Trial",
    "Usage",
    "WinRatePair",
    "__version__",
    "content_hash",
    "resolve_harness_stamp",
    "estimate_cost",
    "is_retryable",
    "native_actions_v1",
    "native_chat_v1",
    "stable_id",
    "VerifierManifest",
    "Capability",
    "DaytonaProvider",
    "DeclarativeImage",
    "DockerProvider",
    "LocalProvider",
    "NetworkMode",
    "ProviderRegistry",
    "SandboxProvider",
    "SandboxRequirements",
]
