"""Compatibility facade for canonical schema-v2 domain contracts.

Canonical definitions live in focused modules under :mod:`plural.agents`,
:mod:`plural.environments`, :mod:`plural.tasks`, :mod:`plural.verifiers`, and
:mod:`plural.jobs`. This facade intentionally preserves the established
``plural.foundation`` import path.
"""

from plural.agents import AgentBinding, AgentDefinition
from plural.common import (
    ErrorCode,
    ExecutionTarget,
    FileDeclaration,
    FrozenModel,
    HarnessBinding,
    HarnessCapability,
    HarnessManifest,
    HarnessPackage,
    PackageSource,
    RoutingSpec,
    canonical_json,
    content_hash,
    stable_id,
)
from plural.environments.manifest import (
    EnvironmentIdentity,
    EnvironmentManifest,
    EnvironmentResource,
    EnvironmentRuntime,
    ExecutionLimits,
    Guardrail,
    HarnessPolicy,
    HarnessStamp,
    NativeAction,
    RewarderDefinition,
    SecretReference,
)
from plural.jobs import (
    ArtifactReference,
    BenchmarkJobSource,
    ExecutionStatus,
    JobLock,
    JobMode,
    JobPlan,
    JobResult,
    JobSource,
    JobSpec,
    ProgressEvent,
    RetryPolicy,
    TaskJobSource,
    TITORecord,
    TrialExecution,
    TrialReceipt,
    TrialResult,
    TrialSpec,
    TrialStatus,
    VerifierResult,
    resolve_trial_harness_stamp,
)
from plural.tasks import BenchmarkDefinition, TaskDefinition
from plural.verifiers import (
    AgentVerifier,
    DeterministicVerifier,
    HumanVerifier,
    RubricCriterion,
    VerifierDefinition,
    VerifierRuntime,
    WeightedVerifier,
)

__all__ = [
    "AgentBinding",
    "AgentDefinition",
    "AgentVerifier",
    "ArtifactReference",
    "BenchmarkDefinition",
    "BenchmarkJobSource",
    "DeterministicVerifier",
    "EnvironmentIdentity",
    "EnvironmentManifest",
    "EnvironmentResource",
    "EnvironmentRuntime",
    "ErrorCode",
    "ExecutionLimits",
    "ExecutionStatus",
    "ExecutionTarget",
    "FileDeclaration",
    "FrozenModel",
    "Guardrail",
    "HarnessBinding",
    "HarnessCapability",
    "HarnessManifest",
    "HarnessPackage",
    "HarnessPolicy",
    "HarnessStamp",
    "HumanVerifier",
    "JobLock",
    "JobMode",
    "JobPlan",
    "JobResult",
    "JobSource",
    "JobSpec",
    "NativeAction",
    "PackageSource",
    "ProgressEvent",
    "RetryPolicy",
    "RewarderDefinition",
    "RoutingSpec",
    "RubricCriterion",
    "SecretReference",
    "TITORecord",
    "TaskDefinition",
    "TaskJobSource",
    "TrialExecution",
    "TrialReceipt",
    "TrialResult",
    "TrialSpec",
    "TrialStatus",
    "VerifierDefinition",
    "VerifierResult",
    "VerifierRuntime",
    "WeightedVerifier",
    "canonical_json",
    "content_hash",
    "resolve_trial_harness_stamp",
    "stable_id",
]
