"""Minimal starting files for a project and each resource kind.

Every place a person must fill in carries a ``PLURAL-TODO`` marker, and
validation reports each remaining marker with its file and line. A fresh
scaffold is therefore never mistaken for a finished resource.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from plural.project.layout import (
    AGENT,
    BENCHMARK,
    ENVIRONMENT,
    HARNESS,
    LOCK_FILE,
    PROJECT_FILE,
    TASK,
    VERIFIER,
    ResourceKind,
)
from plural.project.manifests import PROJECT_SCHEMA_VERSION


@dataclass(frozen=True)
class Scaffold:
    """Files (path to text) and empty directories to create."""

    files: dict[str, str]
    directories: tuple[str, ...] = field(default_factory=tuple)

    def write(self, root: Path, *, overwrite: bool = False) -> list[Path]:
        """Create the scaffold under ``root``, skipping files that already exist.

        Returns:
            Paths that were written.
        """
        written = []
        for directory in self.directories:
            (root / directory).mkdir(parents=True, exist_ok=True)
        for relative, text in self.files.items():
            path = root / relative
            if path.exists() and not overwrite:
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            written.append(path)
        return written


def class_name(name: str) -> str:
    """``support-desk`` -> ``SupportDesk``.

    Returns:
        The class name.
    """
    return "".join(part.capitalize() for part in name.replace("_", "-").split("-") if part)


def title(name: str) -> str:
    """``support-desk`` -> ``Support desk``.

    Returns:
        The title.
    """
    return name.replace("-", " ").capitalize()


MIN_SDK_VERSION = "0.15"
"""The oldest SDK that reads this project layout; new projects require it."""


def project_scaffold(name: str) -> Scaffold:
    """Files for ``plural project init``.

    Returns:
        The project scaffold.
    """
    return Scaffold(
        files={
            PROJECT_FILE: (
                "# Plural project identity. Resources live in the directories beside this file.\n"
                f"schema_version: {PROJECT_SCHEMA_VERSION}\n"
                f"name: {name}\n"
                'description: ""\n'
            ),
            LOCK_FILE: (
                "# Generated by Plural. Commit this file; do not edit it by hand.\n"
                "lock_version: 1\n"
                "resources: {}\n"
            ),
            "pyproject.toml": (
                "[project]\n"
                f'name = "{name}"\n'
                'version = "0.1.0"\n'
                'requires-python = ">=3.11"\n'
                f'dependencies = ["plural>={MIN_SDK_VERSION}"]\n'
            ),
            "README.md": _PROJECT_README.format(name=name),
            ".gitignore": ".plural/\n__pycache__/\n.venv/\n",
        }
    )


_PROJECT_README = """# {name}

A Plural project. Each resource is a directory named after it:

```
environments/<name>/   environment.yaml, environment.py, README.md, resources/
tasks/<name>/          task.yaml, instruction.md, resources/
verifiers/<name>/      verifier.yaml, verify.py
harnesses/<name>/      harness.yaml
agents/<name>/         agent.yaml
benchmarks/<name>/     benchmark.yaml, README.md
```

Common commands, run from anywhere inside this directory:

```bash
plural env init <name>
plural verifier init <name>
plural task init <name> --environment <env> --verifier <verifier>
plural task validate <name>
plural run --task <name> --model <model>
plural project init {name} --push   # register this project with Plural
plural task push <name> --with-deps
```
"""


def resource_scaffold(
    kind: ResourceKind,
    name: str,
    *,
    environment: str | None = None,
    verifiers: tuple[str, ...] = (),
    model: str | None = None,
    harness: str | None = None,
) -> Scaffold:
    """Files for ``plural <kind> init <name>``.

    Returns:
        The resource scaffold, relative to the resource directory.
    """
    cls = class_name(name)
    if kind is ENVIRONMENT:
        return Scaffold(
            files={
                ENVIRONMENT.manifest: _ENVIRONMENT_YAML.format(name=name, cls=cls),
                "environment.py": _ENVIRONMENT_PY.format(title=title(name), cls=cls),
                "README.md": _ENVIRONMENT_README.format(title=title(name)),
            },
            directories=("resources",),
        )
    if kind is TASK:
        environment_line = (
            f"environment: {environment}\n"
            if environment
            else "# PLURAL-TODO: name the one Environment this Task runs in.\n"
            "# environment: <environment-name>\n"
        )
        verifier_lines = (
            "verifiers:\n" + "".join(f"  - {item}\n" for item in verifiers)
            if verifiers
            else "# PLURAL-TODO: name at least one Verifier that scores this Task.\n"
            "# verifiers:\n#   - <verifier-name>\n"
        )
        return Scaffold(
            files={
                TASK.manifest: _TASK_YAML.format(
                    name=name, environment=environment_line, verifiers=verifier_lines
                ),
                "instruction.md": _TASK_INSTRUCTION.format(title=title(name)),
            },
            directories=("resources",),
        )
    if kind is VERIFIER:
        return Scaffold(
            files={
                VERIFIER.manifest: _VERIFIER_YAML.format(name=name),
                "verify.py": _VERIFIER_PY,
            }
        )
    if kind is HARNESS:
        return Scaffold(
            files={
                HARNESS.manifest: _HARNESS_YAML.format(name=name, cls=cls),
                "harness.py": _HARNESS_PY.format(cls=cls),
            }
        )
    if kind is AGENT:
        model_line = (
            f"model: {model}\n"
            if model
            else "# PLURAL-TODO: choose a model from `plural models list`.\n# model: <model-id>\n"
        )
        harness_line = (
            f"harness: {harness}\n"
            if harness
            else "# Optional: a built-in harness (claude-code, codex, hermes) or one in "
            "harnesses/.\n# harness: <harness-name>\n"
        )
        return Scaffold(
            files={
                AGENT.manifest: _AGENT_YAML.format(
                    name=name, model=model_line, harness=harness_line
                )
            }
        )
    if kind is BENCHMARK:
        return Scaffold(
            files={
                BENCHMARK.manifest: _BENCHMARK_YAML.format(name=name),
                "README.md": _BENCHMARK_README.format(title=title(name)),
            }
        )
    raise ValueError(f"no scaffold for {kind.name}")


_ENVIRONMENT_YAML = """\
# Environment: identity, resources, runtime, and settings.
# Behavior (actions, state, observations, rewards) is Python in environment.py.
# README.md explains both to the people who use this Environment.
name: {name}
version: 0.1.0
description: ""
overview: ""
python: environment.py:{cls}
readme: README.md

# Files staged into the runtime, relative to this directory.
resources: []
#  - resources/policy.md

# Where the Environment and Agent run. provider selects a Runtime preset:
# docker (sandboxed), local (a trusted subprocess, not a sandbox), or daytona.
runtime:
  provider: docker
  image: python:3.12-slim

# Settings: which Agent harnesses may run here, and per-Trial limits.
harness_policy:
  mode: allow_all
limits:
  max_turns: 8
  max_seconds: 120
"""

_ENVIRONMENT_PY = '''\
"""{title} Environment.

Actions are the moves an Agent can make. State is private to the Environment;
Verifiers read it and the Agent never does. The Observation is the only thing
the Agent sees. Rewards are per-step credit for training and never contribute
to a Verifier score.
"""

from plural import Environment, Observation, State, action, initial


class {cls}State(State):
    """Private world state."""

    # PLURAL-TODO: declare the fields a Task starts from (with initial()) and the fields actions change.
    goal: str = initial("", description="What this Task asks the Agent to achieve.")
    answer: str = ""
    done: bool = False


class {cls}Observation(Observation):
    """What the Agent sees. Never put answers, scores, or rewards here."""

    goal: str = ""
    done: bool = False


class {cls}(Environment[{cls}Observation, {cls}State]):
    def reset(self, *, seed=None, options=None):
        """Start an episode from the Task's initial state. Called by the Job, not the Agent."""
        _, info = super().reset(seed=seed, options=options)
        self.observation = {cls}Observation(goal=self.state.goal)
        return self.observation, info

    # PLURAL-TODO: replace this action with the moves your Agent needs. Its docstring is the Agent's description.
    @action
    def submit(self, answer: str) -> str:
        """Submit a final answer and end the episode."""
        self.state.answer = answer
        self.state.done = True
        self.observation = {cls}Observation(goal=self.state.goal, done=True)
        return "Submitted."

    def terminated(self) -> bool:
        return self.state.done

    def reward(self, previous_state, current_state, action, result) -> float:
        """Per-step credit for one transition. Recorded for training; never part of the score."""
        return 0.0
'''

_ENVIRONMENT_README = """\
# {title}

## Overview

<!-- PLURAL-TODO: describe the world this Environment simulates and what an Agent does in it. -->

## Actions

Methods marked `@action` in `environment.py`. Their docstrings are what the Agent reads.

## State

Private fields in the `State` class. Fields marked `initial()` are set by each Task's
`initial_state`. The Agent never sees State; Verifiers do.

## Observations

Fields in the `Observation` class: the only thing the Agent sees after each action.

## Rewards

`reward()` returns per-step credit for training. Rewards never contribute to a score.

## Resources

Files listed under `resources:` in `environment.yaml`, staged into the runtime.

## Runtime

`runtime:` in `environment.yaml` says where the Environment and Agent run.

## Settings

`harness_policy` limits which Agent harnesses may run here. `limits` caps each Trial's
turns, seconds, and cost.
"""

_TASK_YAML = """\
# Task: instructions for the Agent, the one Environment it runs in, and the
# Verifiers that score it. Files under resources/ are given to the Agent.
name: {name}
version: 0.1.0
instructions: instruction.md
{environment}{verifiers}# Values for the Environment State fields marked initial().
initial_state: {{}}
"""

_TASK_INSTRUCTION = """\
# {title}

<!-- PLURAL-TODO: write what the Agent must accomplish. Only this text and the Environment's observations reach the Agent. -->
"""

_VERIFIER_YAML = """\
# Verifier: scores a finished episode. Its score, never the step rewards, is
# what Tasks and Benchmarks rank on.
name: {name}
version: 0.1.0
kind: deterministic
check: verify.py:verify
weight: 1
"""

_VERIFIER_PY = '''\
"""Score a finished episode from its final State and Observation."""

from plural import Episode, VerifierOutput


def verify(episode: Episode) -> VerifierOutput:
    """Return a score from 0 to 1 with evidence a reviewer can check."""
    # PLURAL-TODO: compare episode.state with what the Task asked for.
    done = bool(episode.state.get("done"))
    return VerifierOutput(score=float(done), evidence=[f"done={done}"])
'''

_HARNESS_YAML = """\
# Harness: the loop that connects an Agent's model to an Environment.
name: {name}
version: 0.1.0
description: ""
python: harness.py:{cls}Harness
config: {{}}
"""

_HARNESS_PY = '''\
"""A custom Agent interaction loop."""

from plural import Harness, HarnessResult


class {cls}Harness(Harness):
    def run(self, task, agent, environment):
        """Drive one episode. Only observations may reach the model."""
        observation = environment.reset()
        # PLURAL-TODO: call the model with task.instructions and observation, then step the Environment.
        return HarnessResult(response={{"observation": observation}})
'''

_AGENT_YAML = """\
# Agent: a model, its instructions, and an optional harness.
name: {name}
version: 0.1.0
{model}instructions: ""
{harness}"""

_BENCHMARK_YAML = """\
# Benchmark: a named collection of Tasks and the rules for ranking results.
# Results rank on the Verifier score only; step rewards never contribute.
name: {name}
version: 0.1.0
description: ""
# PLURAL-TODO: state the motivation: what this Benchmark measures and why it matters.
purpose: ""
# Add Tasks with `plural benchmark add <task-name> --benchmark {name}`.
tasks: []
scoring:
  metric: Success rate
  # PLURAL-TODO: say what a score means, for example "share of tickets resolved per policy".
  description: ""
  aggregation: weighted_mean
  score_range: [0.0, 1.0]
  success_threshold: 1.0
  # An attempt that ends without a score because of the Agent counts as the lowest score.
  agent_failure: zero
  # Attempts lost to infrastructure are excluded and reported separately.
  infrastructure_error: exclude
"""

_BENCHMARK_README = """\
# {title}

<!-- PLURAL-TODO: explain what this Benchmark measures, who it helps, and what results do not show. -->
"""


__all__ = ["Scaffold", "class_name", "project_scaffold", "resource_scaffold", "title"]
